spring.application.name=customer-service
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
# Management

spring.jackson.default-property-inclusion=always
spring.jackson.serialization.write-dates-as-timestamps=false
# Jackson

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Eureka Discovery

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:customers-db
server.port=8081

