spring.application.name=discovery-service
server.port=8761

# Eureka
eureka.instance.prefer-ip-address=true
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.server.enable-self-preservation=true

# Management
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

